#################################################
## SHADDOCK: Services Configuration Definition ##
#################################################

# All this variables will be passed as environment
# variables to the containers.

template_vars:
    HOST_NAME: <your_hostname>
    HOST_IP: 10.0.0.20
    RABBITMQ_HOST: 10.0.0.20
    RABBIT_PASS: panama
    MYSQL_DB: 10.0.0.20
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    KEYSTONE_DBPASS: panama
    DEMO_PASS: panama
    ADMIN_TOKEN: panama
    ADMIN_PASS: panama
    GLANCE_DBPASS: panama
    GLANCE_PASS: panama
    NOVA_DBPASS: panama
    NOVA_PASS: panama
    DASH_DBPASS: panama
    CINDER_DBPASS: panama
    CINDER_PASS: panama
    NEUTRON_DBPASS: panama
    NEUTRON_PASS: panama
    HEAT_DBPASS: panama
    HEAT_PASS: panama
    CEILOMETER_DBPASS: panama
    CEILOMETER_PASS: panama
    TROVE_DBPASS: panama
    TROVE_PASS: panama
    MURANO_DBPASS: panama
    MURANO_PASS: panama
    MISTRAL_PASS: panama
    MISTRAL_DBPASS: panama
    OS_MISTRAL_URL: http://10.0.0.20:8989/v2
    no_proxy: '16.49.136.0/22, 127.0.0.1, localhost'
