##############################################
## SHADDOCK: Services Architecture Definition ##
##############################################

rabbitmq:
  priority: 10
  ports:
    - 5672
    - 15672
  volumes:
    '/data/log': '/var/lib/rabbitmq/log'
    '/data/mnesia': '/var/lib/rabbitmq/mnesia'
  depend-on: None


mysql:
  priority: 20
  ports:
    - 3306
  volumes:
    '/var/log/supervisor': '/var/log/shaddock/mysql'
  depend-on: None


keystone:
  priority: 30
  ports:
    - 35357
    - 5000
  volumes:
    '/var/log/supervisor': '/var/log/shaddock/keystone'
  depend-on:
    mysql:
      - tcp: 3306
      - state: running
    rabbitmq:
      - tcp: 5672
      - tcp: 15672
      - state: running


nova:
  priority: 40
  ports:
    - 8774
    - 8775
  volumes:
    '/var/log/nova': '/var/log/shaddock/nova'
  privileged: True
  depend-on:
    keystone:
     - tcp: 5000
     - tcp: 35357
     - state: running
    config:
      - state: stoped
      - grep-logs: service_id


glance:
  priority: 50
  ports:
    - 9292
    - 4324
  volumes:
    '/var/log/supervisor': '/var/log/shaddock/glance'
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - http: (url, code)
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


horizon:
  priority: 60
  ports:
    - 80
    - 11211
  volumes:
    '/var/log/supervisor': '/var/log/shaddock/horizon'
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


nova-compute:
  volumes:
    '/var/log/nova': '/var/log/shaddock/compute'
  privileged: True
  network_mode: host
  priority: 90
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


mistral:
  ports:
    - 8989
  priority: 90
  volumes:
    '/var/log/supervisor': '/var/log/shaddock/mistral'
  depend-on:
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running
