###############################################
## PANAMA: Services Configuration Definition ##
###############################################

# All this variables will be passed as environment
# variables to the containers.

template_vars:
    HOST_NAME: lapierrt-wn
    HOST_IP: '16.49.138.223'
    RABBITMQ_HOST: '16.49.138.223'
    RABBIT_PASS: panamassword
    MYSQL_DB: '16.49.138.223'
    EMAIL_ADDRESS: example.com
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    KEYSTONE_DBPASS: panamassword
    DEMO_PASS: panamassword
    ADMIN_TOKEN: panamassword
    ADMIN_PASS: panamassword
    GLANCE_DBPASS: panamassword
    GLANCE_PASS: panamassword
    NOVA_DBPASS: panamassword
    NOVA_PASS: panamassword
    DASH_DBPASS: panamassword
    CINDER_DBPASS: panamassword
    CINDER_PASS: panamassword
    NEUTRON_DBPASS: panamassword
    NEUTRON_PASS: panamassword
    HEAT_DBPASS: panamassword
    HEAT_PASS: panamassword
    CEILOMETER_DBPASS: panamassword
    CEILOMETER_PASS: panamassword
    TROVE_DBPASS: panamassword
    TROVE_PASS: panamassword
    MURANO_DBPASS: panamassword
    MURANO_PASS: panamassword
    MISTRAL_PASS: panamassword
    MISTRAL_DBPASS: panamassword
    OS_MISTRAL_URL: http://16.49.138.223:8989/v2
    no_proxy: '16.49.136.0/22, 127.0.0.1, localhost'