###############################################
## PANAMA: Services Configuration Definition ##
###############################################

template_vars:
    HOST_NAME: your_host_name
    HOST_IP: your_host_ip
    RABBITMQ_HOST: your_host_ip
    MYSQL_DB: your_host_ip
    #For one node installation all the hosts are your IP
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    RABBITMQ_PASSWORD: password
    GLANCE_DBPASS: password
    ADMIN_TOKEN: password
    KEYSTONE_DBPASS: password
    NOVA_DBPASS: password
    ADMIN_PASS: password

