##############################################
## PANAMA: Services Architecture Definition ##
##############################################

rabbitmq:
  ports:
    - 5672
    - 15672
  volumes:
    '/data/log': '/var/lib/rabbitmq/log'
    '/data/mnesia': '/var/lib/rabbitmq/mnesia'
  privileged: false
  priority: 10
  depend-on: None


mysql:
  ports:
    - 3306
  volumes:
    '/var/log/supervisor': '/var/log/panama/mysql'
  privileged: false
  priority: 20
  depend-on: None


keystone:
  ports:
    - 35357
    - 5000
  volumes:
    '/var/log/supervisor': '/var/log/panama/keystone'
  privileged: false
  priority: 30
  depend-on:
    mysql:
      - tcp: 3306
      - state: running
    rabbitmq:
      - tcp: 5672
      - tcp: 15672
      - state: running


nova:
  ports:
    - 8774
    - 8775
    - 9696
  volumes:
    '/var/log/supervisor': '/var/log/panama/nova'
  privileged: true
  priority: 40
  depend-on:
    keystone:
     - tcp: 5000
     - tcp: 35357
     - state: running
    config:
      - state: finnished
      - grep-logs: service_id


glance:
  ports: 
    - 9292
    - 4324
  volumes: 
    '/var/log/supervisor': '/var/log/panama/glance'
  privileged: false
  priority: 50
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


horizon:
  ports:
    - 80
    - 11211 
  volumes:
    '/var/log/supervisor': '/var/log/panama/horizon'
  privileged: false
  priority: 60
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


neutron:
  ports:
    - 80
    - 11211
  volumes:
    '/var/log/supervisor': '/var/log/panama/neutron'
  privileged: false
  priority: 70
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


cinder:
  ports:
    - 80
    - 11211
  volumes:
    '/var/log/supervisor': '/var/log/panama/cinder'
  privileged: false
  priority: 80
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running


nova-compute:
  ports:
    - 90
    - 11211
  volumes:
    '/var/log/supervisor': '/var/log/panama/cinder'
  privileged: false
  priority: 90
  depend-on:
    nova:
      - tcp: 8774
      - tcp: 8775
      - state: running
    mysql:
      - tcp: 3306
      - state: running
    keystone:
      - tcp: 35357
      - tcp: 5000
      - state: running
