##############################################
## PANAMA: Services Architecture Definition ##
##############################################

glance:
  ports: 
    - 9292
    - 4324
  volumes: 
    '/var/log/supervisor': '/var/log/panama/glance'
  privileged: false
  priority: 50


horizon:
  ports:
    - 80
    - 11211 
  volumes:
    '/var/log/supervisor': '/var/log/panama/horizon'
  privileged: false
  priority: 60


keystone:
  ports:
    - 35357
    - 5000
  volumes:
    '/var/log/supervisor': '/var/log/panama/keystone'
  privileged: false
  priority: 30


mysql:
  ports:
    - 3306
  volumes:
    '/var/log/supervisor': '/var/log/panama/mysql'
  privileged: false
  priority: 20


nova:
  ports:
    - 8774
    - 8775
  volumes:
    '/var/log/supervisor': '/var/log/panama/nova'
  privileged: true
  priority: 40


rabbitmq:
  ports:
    - 5672
    - 15672
  volumes:
    '/data/log': '/var/lib/rabbitmq/log'
    '/data/mnesia': '/var/lib/rabbitmq/mnesia'
  privileged: false
  priority: 10

